export const LOAD_ALL_USER_BY_USERNAME = 'LOAD_ALL_USER_BY_USERNAME';
export const LOAD_ALL_USER = 'LOAD_ALL_USER';
export const DELETE_USER = 'DELETE_USER';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';